### PR TITLE
Add label model and associate labels when creating issues

### PR DESCRIPTION
**Pull request by awaxman11**
Pretty much ready to do expect one issue:
-  repo_id's are not associated properly when creating labels, which is causing the repo_id property of labels to be ```nil```: https://github.com/CarlosPlusPlus/ghanban/issues/13

### CODE REVIEW

**Comment by awaxman11** [comment]
@CarlosPlusPlus this should be good to go!

**Comment by CarlosPlusPlus** [comment]
Decided to make a commit to the branch, @awaxman11 --- looks like `first_or_create` can take an optional block which only gets run _if the object created is brand new_ (just created).

So now, this is what our loop looks like, with only one (1) DB query now:

```ruby
params['board']['repos'].collect do |name|
  repo = Repo.where(name: name).first_or_create { @new_repo = true }

  if @new_repo
    repo.add_issues(@client.issues(name, state: 'all'))
    @new_repo = false
  end

  @board.repos << repo
end
```

I'll try to think if there's a better way to do this, but for sure, creating a variable is far less expensive than hitting the database one extra time per repo. :smile:

**Comment by CarlosPlusPlus** [comment]
Also, there may be a potential bug here. Is the goal to import *all* labels tied to a given repository? With the way the code is structured right now, we only pull in the specific labels *tied to issues*. For example, when looking at the `awaxman11/gvents` `Repo`, there are only four (4) associated `Label` instances:

gvents_labels

In reality, there should be total of eight (8) labels:
https://github.com/awaxman11/gvents/labels

Thoughts?

**Comment by awaxman11** [comment]
Yeah that's a good point. We're going to need to make an additional call to grab on the labels. Now that you mention it, it may make sense to import all the labels and than associate them with the specific issues once that is done.

What do you think?

**Comment by CarlosPlusPlus** [comment]
Definitely on board with the latter path forward. :+1: 
Our goal should always be to minimize API calls.

We can make one API call to grab all of the labels --- at that point, since we are already parsing through the issues JSON, we can simply look at our new list of labels and assign to issues accordingly. We know the labels will _have_ to exist - the benefit now is that we're querying ourselves (internal DB) vs. the API.

**Comment by awaxman11** [comment]
Just pushed a change to add all labels from a repo. 

Should be good to go now :+1:

**Comment by CarlosPlusPlus** [comment]
PR has been tested and will be merged, @awaxman11.

*****

One important point of information --- I did my testing by importing three (3) repositories:
* awaxman11/gvents
* CarlosPlusPlus/ghanban
* CarlosPlusPlus/swoonatra

Here's the output from our Rails server regarding request completion time:

```Completed 200 OK in 2563ms (Views: 374.6ms | ActiveRecord: 134.2ms)```

~ 2.5s to complete the request - not terrible, but the less information we (1) request and (2) save to the database, the better and more performant this will become. I'll look into some of the queries being done a little later and see if we can optimize our time.

**Comment by awaxman11** [comment]
>~ 2.5s to complete the request - not terrible, but the less information we (1) request and (2) save to the database, the better, faster, and more performant this will become

Agreed. Unfortunately I think that this process is going to end up taking a fair amount of time to import large repos. For example the SG repo has ~10,000 issues (includes open and closed)

**Comment by CarlosPlusPlus** [comment]
Absolutely re: your last point on the amount of issues - totally understood. Besides, we should be able to get all of those in one (1) API call. I suspect that _most_ public repos also won't have 10k issues.

My point was that we should try to minimize API / DB calls in whatever we do. For example, right now, we do a `Label.find_or_create` N times for each `Issue`, where N is the # of `Label` objects the issue should have associated. That is a _ton_ of DB calls - multiply those by the # of people using the site and the DB can choke real quick.

I make it a point to always look at `rails s` or the logs for things that look weird - seeing very similar SQL being fired off makes me think we can do this better. On my never ending list of things to do. :smile:

**Comment by awaxman11** [comment]
Yeah that makes a lot of sense. Regardless of how many issues we need to pull in, we should always try and minimize the number of API / DB calls that we make. Scaling / efficiency has never been one of my strengths :)

**Pull request merged**
